data = {1: {'dmg': 0,
     'id': 1,
     'maxSize': 64,
     'name': 'Stone',
     'qty': 2844,
     'rawName': 'tile.stone'},
 2: {'dmg': 0,
     'id': 2,
     'maxSize': 64,
     'name': 'Grass Block',
     'qty': 5008,
     'rawName': 'tile.grass'},
 3: {'dmg': 0,
     'id': 3,
     'maxSize': 64,
     'name': 'Dirt',
     'qty': 731,
     'rawName': 'tile.dirt'},
 4: {'dmg': 0,
     'id': 4,
     'maxSize': 64,
     'name': 'Cobblestone',
     'qty': 250,
     'rawName': 'tile.stonebrick'},
 5: {'dmg': 0,
     'id': 5,
     'maxSize': 64,
     'name': 'Oak Wood Planks',
     'qty': 432,
     'rawName': 'tile.wood.oak'},
 6: {'dmg': 0,
     'id': 6,
     'maxSize': 64,
     'name': 'Oak Sapling',
     'qty': 146,
     'rawName': 'tile.sapling.oak'},
 7: {'dmg': 0,
     'id': 12,
     'maxSize': 64,
     'name': 'Sand',
     'qty': 89,
     'rawName': 'tile.sand'},
 8: {'dmg': 0,
     'id': 13,
     'maxSize': 64,
     'name': 'Gravel',
     'qty': 5004,
     'rawName': 'tile.gravel'},
 9: {'dmg': 0,
     'id': 17,
     'maxSize': 64,
     'name': 'Oak Wood',
     'qty': 340,
     'rawName': 'tile.log.oak'},
 10: {'dmg': 0,
      'id': 18,
      'maxSize': 64,
      'name': 'Oak Leaves',
      'qty': 250,
      'rawName': 'tile.leaves.oak'},
 11: {'dmg': 0,
      'id': 20,
      'maxSize': 64,
      'name': 'Glass',
      'qty': 319,
      'rawName': 'tile.glass'},
 12: {'dmg': 0,
      'id': 21,
      'maxSize': 64,
      'name': 'Lapis Lazuli Ore',
      'qty': 1,
      'rawName': 'tile.orelapis'},
 13: {'dmg': 0,
      'id': 22,
      'maxSize': 64,
      'name': 'Lapis Lazuli Block',
      'qty': 54,
      'rawName': 'tile.blocklapis'},
 14: {'dmg': 0,
      'id': 29,
      'maxSize': 64,
      'name': 'Sticky Piston',
      'qty': 4,
      'rawName': 'tile.pistonstickybase'},
 15: {'dmg': 0,
      'id': 33,
      'maxSize': 64,
      'name': 'Piston',
      'qty': 9,
      'rawName': 'tile.pistonbase'},
 16: {'dmg': 0,
      'id': 35,
      'maxSize': 64,
      'name': 'Wool',
      'qty': 54,
      'rawName': 'tile.cloth.white'},
 17: {'dmg': 0,
      'id': 37,
      'maxSize': 64,
      'name': 'Flower',
      'qty': 3,
      'rawName': 'tile.flower'},
 18: {'dmg': 0,
      'id': 38,
      'maxSize': 64,
      'name': 'Rose',
      'qty': 6,
      'rawName': 'tile.rose'},
 19: {'dmg': 0,
      'id': 39,
      'maxSize': 64,
      'name': 'Mushroom',
      'qty': 41,
      'rawName': 'tile.mushroom'},
 20: {'dmg': 0,
      'id': 40,
      'maxSize': 64,
      'name': 'Mushroom',
      'qty': 20,
      'rawName': 'tile.mushroom'},
 21: {'dmg': 0,
      'id': 44,
      'maxSize': 64,
      'name': 'Stone Slab',
      'qty': 70,
      'rawName': 'tile.stoneslab.stone'},
 22: {'dmg': 0,
      'id': 49,
      'maxSize': 64,
      'name': 'Obsidian',
      'qty': 1026,
      'rawName': 'tile.obsidian'},
 23: {'dmg': 0,
      'id': 50,
      'maxSize': 64,
      'name': 'Torch',
      'qty': 224,
      'rawName': 'tile.torch'},
 24: {'dmg': 0,
      'id': 53,
      'maxSize': 64,
      'name': 'Oak Wood Stairs',
      'qty': 74,
      'rawName': 'tile.stairswood'},
 25: {'dmg': 0,
      'id': 54,
      'maxSize': 64,
      'name': 'Chest',
      'qty': 56,
      'rawName': 'tile.chest'},
 26: {'dmg': 0,
      'id': 58,
      'maxSize': 64,
      'name': 'Crafting Table',
      'qty': 15,
      'rawName': 'tile.workbench'},
 27: {'dmg': 0,
      'id': 61,
      'maxSize': 64,
      'name': 'Furnace',
      'qty': 394,
      'rawName': 'tile.furnace'},
 28: {'dmg': 0,
      'id': 65,
      'maxSize': 64,
      'name': 'Ladder',
      'qty': 61,
      'rawName': 'tile.ladder'},
 29: {'dmg': 0,
      'id': 67,
      'maxSize': 64,
      'name': 'Stone Stairs',
      'qty': 1,
      'rawName': 'tile.stairsstone'},
 30: {'dmg': 0,
      'id': 69,
      'maxSize': 64,
      'name': 'Lever',
      'qty': 50,
      'rawName': 'tile.lever'},
 31: {'dmg': 0,
      'id': 70,
      'maxSize': 64,
      'name': 'Pressure Plate',
      'qty': 1,
      'rawName': 'tile.pressureplate'},
 32: {'dmg': 0,
      'id': 72,
      'maxSize': 64,
      'name': 'Pressure Plate',
      'qty': 3,
      'rawName': 'tile.pressureplate'},
 33: {'dmg': 0,
      'id': 76,
      'maxSize': 64,
      'name': 'Redstone Torch',
      'qty': 54,
      'rawName': 'tile.notgate'},
 34: {'dmg': 0,
      'id': 81,
      'maxSize': 64,
      'name': 'Cactus',
      'qty': 21,
      'rawName': 'tile.cactus'},
 35: {'dmg': 0,
      'id': 82,
      'maxSize': 64,
      'name': 'Clay',
      'qty': 111,
      'rawName': 'tile.clay'},
 36: {'dmg': 0,
      'id': 85,
      'maxSize': 64,
      'name': 'Fence',
      'qty': 213,
      'rawName': 'tile.fence'},
 37: {'dmg': 0,
      'id': 87,
      'maxSize': 64,
      'name': 'Netherrack',
      'qty': 516,
      'rawName': 'tile.hellrock'},
 38: {'dmg': 0,
      'id': 89,
      'maxSize': 64,
      'name': 'Glowstone',
      'qty': 11,
      'rawName': 'tile.lightgem'},
 39: {'dmg': 0,
      'id': 96,
      'maxSize': 64,
      'name': 'Trapdoor',
      'qty': 2,
      'rawName': 'tile.trapdoor'},
 40: {'dmg': 0,
      'id': 98,
      'maxSize': 64,
      'name': 'Stone Bricks',
      'qty': 59,
      'rawName': 'tile.stonebricksmooth.default'},
 41: {'dmg': 0,
      'id': 101,
      'maxSize': 64,
      'name': 'Iron Bars',
      'qty': 32,
      'rawName': 'tile.fenceiron'},
 42: {'dmg': 0,
      'id': 102,
      'maxSize': 64,
      'name': 'Glass Pane',
      'qty': 39,
      'rawName': 'tile.thinglass'},
 43: {'dmg': 0,
      'id': 112,
      'maxSize': 64,
      'name': 'Nether Brick',
      'qty': 12,
      'rawName': 'tile.netherbrick'},
 44: {'dmg': 0,
      'id': 113,
      'maxSize': 64,
      'name': 'Nether Brick Fence',
      'qty': 2,
      'rawName': 'tile.netherfence'},
 45: {'dmg': 0,
      'id': 126,
      'maxSize': 64,
      'name': 'Oak Wood Slab',
      'qty': 47,
      'rawName': 'tile.woodslab.oak'},
 46: {'dmg': 0,
      'id': 143,
      'maxSize': 64,
      'name': 'Button',
      'qty': 2,
      'rawName': 'tile.button'},
 47: {'dmg': 0,
      'id': 146,
      'maxSize': 64,
      'name': 'Trapped Chest',
      'qty': 3,
      'rawName': 'tile.chesttrap'},
 48: {'dmg': 0,
      'id': 154,
      'maxSize': 64,
      'name': 'Hopper',
      'qty': 9,
      'rawName': 'tile.hopper'},
 49: {'dmg': 0,
      'id': 260,
      'maxSize': 64,
      'name': 'Apple',
      'qty': 9,
      'rawName': 'item.apple'},
 50: {'dmg': 0,
      'id': 262,
      'maxSize': 64,
      'name': 'Arrow',
      'qty': 5,
      'rawName': 'item.arrow'},
 51: {'dmg': 0,
      'id': 263,
      'maxSize': 64,
      'name': 'Coal',
      'qty': 4791,
      'rawName': 'item.coal'},
 52: {'dmg': 0,
      'id': 264,
      'maxSize': 64,
      'name': 'Diamond',
      'qty': 30,
      'rawName': 'item.diamond'},
 53: {'dmg': 0,
      'id': 265,
      'maxSize': 64,
      'name': 'Iron Ingot',
      'qty': 1447,
      'rawName': 'item.ingotiron'},
 54: {'dmg': 0,
      'id': 266,
      'maxSize': 64,
      'name': 'Gold Ingot',
      'qty': 384,
      'rawName': 'item.ingotgold'},
 55: {'dmg': 0,
      'id': 275,
      'maxSize': 1,
      'name': 'Stone Axe',
      'qty': 12,
      'rawName': 'item.hatchetstone'},
 56: {'dmg': 0,
      'id': 280,
      'maxSize': 64,
      'name': 'Stick',
      'qty': 322,
      'rawName': 'item.stick'},
 57: {'dmg': 0,
      'id': 281,
      'maxSize': 64,
      'name': 'Bowl',
      'qty': 4,
      'rawName': 'item.bowl'},
 58: {'dmg': 0,
      'id': 287,
      'maxSize': 64,
      'name': 'String',
      'qty': 29,
      'rawName': 'item.string'},
 59: {'dmg': 0,
      'id': 288,
      'maxSize': 64,
      'name': 'Feather',
      'qty': 33,
      'rawName': 'item.feather'},
 60: {'dmg': 0,
      'id': 289,
      'maxSize': 64,
      'name': 'Gunpowder',
      'qty': 55,
      'rawName': 'item.sulphur'},
 61: {'dmg': 0,
      'id': 295,
      'maxSize': 64,
      'name': 'Seeds',
      'qty': 222,
      'rawName': 'item.seeds'},
 62: {'dmg': 0,
      'id': 296,
      'maxSize': 64,
      'name': 'Wheat',
      'qty': 43,
      'rawName': 'item.wheat'},
 63: {'dmg': 0,
      'id': 308,
      'maxSize': 1,
      'name': 'Iron Leggings',
      'qty': 1,
      'rawName': 'item.leggingsiron'},
 64: {'dmg': 0,
      'id': 309,
      'maxSize': 1,
      'name': 'Iron Boots',
      'qty': 1,
      'rawName': 'item.bootsiron'},
 65: {'dmg': 0,
      'id': 318,
      'maxSize': 64,
      'name': 'Flint',
      'qty': 749,
      'rawName': 'item.flint'},
 66: {'dmg': 0,
      'id': 323,
      'maxSize': 16,
      'name': 'Sign',
      'qty': 420,
      'rawName': 'item.sign'},
 67: {'dmg': 0,
      'id': 324,
      'maxSize': 16,
      'name': 'Wooden Door',
      'qty': 7,
      'rawName': 'item.doorwood'},
 68: {'dmg': 0,
      'id': 325,
      'maxSize': 16,
      'name': 'Bucket',
      'qty': 3,
      'rawName': 'item.bucket'},
 69: {'dmg': 0,
      'id': 331,
      'maxSize': 64,
      'name': 'Redstone',
      'qty': 1345,
      'rawName': 'item.redstone'},
 70: {'dmg': 0,
      'id': 334,
      'maxSize': 64,
      'name': 'Leather',
      'qty': 10,
      'rawName': 'item.leather'},
 71: {'dmg': 0,
      'id': 337,
      'maxSize': 64,
      'name': 'Clay',
      'qty': 2,
      'rawName': 'item.clay'},
 72: {'dmg': 0,
      'id': 338,
      'maxSize': 64,
      'name': 'Sugar Canes',
      'qty': 35,
      'rawName': 'item.reeds'},
 73: {'dmg': 0,
      'id': 339,
      'maxSize': 64,
      'name': 'Paper',
      'qty': 19,
      'rawName': 'item.paper'},
 74: {'dmg': 0,
      'id': 340,
      'maxSize': 64,
      'name': 'Book',
      'qty': 2,
      'rawName': 'item.book'},
 75: {'dmg': 0,
      'id': 341,
      'maxSize': 64,
      'name': 'Slimeball',
      'qty': 3,
      'rawName': 'item.slimeball'},
 76: {'dmg': 0,
      'id': 344,
      'maxSize': 16,
      'name': 'Egg',
      'qty': 2,
      'rawName': 'item.egg'},
 77: {'dmg': 0,
      'id': 348,
      'maxSize': 64,
      'name': 'Glowstone Dust',
      'qty': 224,
      'rawName': 'item.yellowdust'},
 78: {'dmg': 0,
      'id': 351,
      'maxSize': 64,
      'name': 'Ink Sac',
      'qty': 6,
      'rawName': 'item.dyepowder.black'},
 79: {'dmg': 0,
      'id': 352,
      'maxSize': 64,
      'name': 'Bone',
      'qty': 49,
      'rawName': 'item.bone'},
 80: {'dmg': 0,
      'id': 363,
      'maxSize': 64,
      'name': 'Raw Beef',
      'qty': 31,
      'rawName': 'item.beefraw'},
 81: {'dmg': 0,
      'id': 365,
      'maxSize': 64,
      'name': 'Raw Chicken',
      'qty': 4,
      'rawName': 'item.chickenraw'},
 82: {'dmg': 0,
      'id': 367,
      'maxSize': 64,
      'name': 'Rotten Flesh',
      'qty': 209,
      'rawName': 'item.rottenflesh'},
 83: {'dmg': 0,
      'id': 368,
      'maxSize': 16,
      'name': 'Ender Pearl',
      'qty': 2,
      'rawName': 'item.enderpearl'},
 84: {'dmg': 0,
      'id': 369,
      'maxSize': 64,
      'name': 'Blaze Rod',
      'qty': 9,
      'rawName': 'item.blazerod'},
 85: {'dmg': 0,
      'id': 371,
      'maxSize': 64,
      'name': 'Gold Nugget',
      'qty': 137,
      'rawName': 'item.goldnugget'},
 86: {'dmg': 0,
      'id': 373,
      'maxSize': 1,
      'name': 'Water Bottle',
      'qty': 51,
      'rawName': 'item.potion'},
 87: {'dmg': 0,
      'id': 374,
      'maxSize': 64,
      'name': 'Glass Bottle',
      'qty': 8,
      'rawName': 'item.glassbottle'},
 88: {'dmg': 0,
      'id': 375,
      'maxSize': 64,
      'name': 'Spider Eye',
      'qty': 14,
      'rawName': 'item.spidereye'},
 89: {'dmg': 0,
      'id': 391,
      'maxSize': 64,
      'name': 'Carrot',
      'qty': 134,
      'rawName': 'item.carrots'},
 90: {'dmg': 0,
      'id': 392,
      'maxSize': 64,
      'name': 'Potato',
      'qty': 30,
      'rawName': 'item.potato'},
 91: {'dmg': 0,
      'id': 406,
      'maxSize': 64,
      'name': 'Nether Quartz',
      'qty': 1442,
      'rawName': 'item.netherquartz'},
 92: {'dmg': 0,
      'id': 506,
      'maxSize': 64,
      'name': 'tile.engineWood',
      'qty': 4,
      'rawName': 'tile.enginewood'},
 93: {'dmg': 0,
      'id': 507,
      'maxSize': 64,
      'name': 'tile.fillerBlock',
      'qty': 1,
      'rawName': 'tile.fillerblock'},
 94: {'dmg': 0,
      'id': 511,
      'maxSize': 64,
      'name': 'tile.markerBlock',
      'qty': 12,
      'rawName': 'tile.markerblock'},
 95: {'dmg': 0,
      'id': 520,
      'maxSize': 64,
      'name': 'tile.tankBlock',
      'qty': 8,
      'rawName': 'tile.tankblock'},
 96: {'dmg': 0,
      'id': 524,
      'maxSize': 64,
      'name': 'Electrical Engine',
      'qty': 13,
      'rawName': 'tile.for.engine.0'},
 97: {'dmg': 0,
      'id': 534,
      'maxSize': 64,
      'name': 'Apatite Ore',
      'qty': 114,
      'rawName': 'tile.resources.0'},
 98: {'dmg': 0,
      'id': 601,
      'maxSize': 64,
      'name': 'ic2.blockAlloyGlass',
      'qty': 6,
      'rawName': 'ic2.blockalloyglass'},
 99: {'dmg': 0,
      'id': 608,
      'maxSize': 64,
      'name': 'ic2.blockBatBox',
      'qty': 5,
      'rawName': 'ic2.blockbatbox'},
 100: {'dmg': 0,
       'id': 609,
       'maxSize': 64,
       'name': 'ic2.blockFenceIron',
       'qty': 10,
       'rawName': 'ic2.blockfenceiron'},
 101: {'dmg': 0,
       'id': 611,
       'maxSize': 64,
       'name': 'ic2.blockGenerator',
       'qty': 67,
       'rawName': 'ic2.blockgenerator'},
 102: {'dmg': 0,
       'id': 616,
       'maxSize': 64,
       'name': 'ic2.blockLuminatorDark',
       'qty': 6,
       'rawName': 'ic2.blockluminatordark'},
 103: {'dmg': 0,
       'id': 617,
       'maxSize': 64,
       'name': 'ic2.blockMachine',
       'qty': 120,
       'rawName': 'ic2.blockmachine'},
 104: {'dmg': 0,
       'id': 625,
       'maxSize': 64,
       'name': 'ic2.blockOreUran',
       'qty': 121,
       'rawName': 'ic2.blockoreuran'},
 105: {'dmg': 0,
       'id': 629,
       'maxSize': 64,
       'name': 'ic2.blockRubSapling',
       'qty': 67,
       'rawName': 'ic2.blockrubsapling'},
 106: {'dmg': 0,
       'id': 641,
       'maxSize': 64,
       'name': 'Iron Chest',
       'qty': 5,
       'rawName': 'tile.ironchest:iron'},
 107: {'dmg': 0,
       'id': 724,
       'maxSize': 64,
       'name': 'tile.enderIO:blockCrusher.name',
       'qty': 2,
       'rawName': 'tile.enderio:blockcrusher'},
 108: {'dmg': 0,
       'id': 790,
       'maxSize': 64,
       'name': 'Vinteum Ore',
       'qty': 238,
       'rawName': 'tile.arsmagica2:ores.0'},
 109: {'dmg': 0,
       'id': 813,
       'maxSize': 64,
       'name': 'Aum',
       'qty': 1,
       'rawName': 'tile.arsmagica2:aum'},
 110: {'dmg': 0,
       'id': 815,
       'maxSize': 64,
       'name': 'Tarma Root',
       'qty': 2,
       'rawName': 'tile.arsmagica2:tarmaroot'},
 111: {'dmg': 0,
       'id': 816,
       'maxSize': 64,
       'name': 'Witchwood Log',
       'qty': 25,
       'rawName': 'tile.arsmagica2:witchwoodlog'},
 112: {'dmg': 0,
       'id': 817,
       'maxSize': 64,
       'name': 'Witchwood Leaves',
       'qty': 10,
       'rawName': 'tile.arsmagica2:witchwoodleaves'},
 113: {'dmg': 0,
       'id': 861,
       'maxSize': 64,
       'name': 'AppEng.Blocks.ExportBusPrecision.name',
       'qty': 2,
       'rawName': 'appeng.blocks.exportbusprecision'},
 114: {'dmg': 0,
       'id': 862,
       'maxSize': 64,
       'name': 'AppEng.Blocks.OreQuartz.name',
       'qty': 94,
       'rawName': 'appeng.blocks.orequartz'},
 115: {'dmg': 0,
       'id': 1004,
       'maxSize': 64,
       'name': 'Dark Iron Ore',
       'qty': 2,
       'rawName': 'tile.factorization:darkironore'},
 116: {'dmg': 0,
       'id': 1471,
       'maxSize': 64,
       'name': 'Tool Station',
       'qty': 1,
       'rawName': 'toolstation.crafter'},
 117: {'dmg': 0,
       'id': 1485,
       'maxSize': 64,
       'name': 'Iron Oreberry Bush',
       'qty': 4,
       'rawName': 'block.oreberry.iron'},
 118: {'dmg': 0,
       'id': 1486,
       'maxSize': 64,
       'name': 'Aluminum Oreberry Bush',
       'qty': 4,
       'rawName': 'block.oreberry.aluminum'},
 119: {'dmg': 0,
       'id': 1754,
       'maxSize': 64,
       'name': 'tile.hive.curious.name',
       'qty': 1,
       'rawName': 'tile.hive.curious'},
 120: {'dmg': 0,
       'id': 2130,
       'maxSize': 64,
       'name': 'Ruby Ore',
       'qty': 1,
       'rawName': 'tile.projectred.exploration.ore.oreruby'},
 121: {'dmg': 0,
       'id': 2131,
       'maxSize': 64,
       'name': 'Marble',
       'qty': 6183,
       'rawName': 'tile.projectred.exploration.stone.stonemarble'},
 122: {'dmg': 0,
       'id': 2224,
       'maxSize': 64,
       'name': 'tile.extrabiomes.sapling.bald_cypress.name',
       'qty': 759,
       'rawName': 'tile.extrabiomes.sapling.bald_cypress'},
 123: {'dmg': 0,
       'id': 2225,
       'maxSize': 64,
       'name': 'tile.extrabiomes.baldcypressquarter.name',
       'qty': 64,
       'rawName': 'tile.extrabiomes.baldcypressquarter'},
 124: {'dmg': 0,
       'id': 2227,
       'maxSize': 64,
       'name': 'tile.extrabiomes.cypresskneelog.name',
       'qty': 28,
       'rawName': 'tile.extrabiomes.cypresskneelog'},
 125: {'dmg': 0,
       'id': 2257,
       'maxSize': 1,
       'name': 'Music Disc',
       'qty': 1,
       'rawName': 'item.record'},
 126: {'dmg': 0,
       'id': 2259,
       'maxSize': 1,
       'name': 'Music Disc',
       'qty': 1,
       'rawName': 'item.record'},
 127: {'dmg': 0,
       'id': 2263,
       'maxSize': 1,
       'name': 'Music Disc',
       'qty': 1,
       'rawName': 'item.record'},
 128: {'dmg': 0,
       'id': 2266,
       'maxSize': 1,
       'name': 'Music Disc',
       'qty': 1,
       'rawName': 'item.record'},
 129: {'dmg': 0,
       'id': 2428,
       'maxSize': 64,
       'name': 'Cinnabar Ore',
       'qty': 100,
       'rawName': 'tile.blockcustomore.0'},
 130: {'dmg': 0,
       'id': 2525,
       'maxSize': 64,
       'name': 'tile.extrautils:plant/ender_lilly.name',
       'qty': 5,
       'rawName': 'tile.extrautils:plant/ender_lilly'},
 131: {'dmg': 0,
       'id': 2548,
       'maxSize': 64,
       'name': 'Tank',
       'qty': 1,
       'rawName': 'tile.openblocks.tank'},
 132: {'dmg': 0,
       'id': 2790,
       'maxSize': 64,
       'name': 'Ultra Low Voltage Windmill',
       'qty': 6,
       'rawName': 'aroma1997.elv'},
 133: {'dmg': 0,
       'id': 2850,
       'maxSize': 64,
       'name': 'powerconverters.common.bridge.name',
       'qty': 1,
       'rawName': 'powerconverters.common.bridge'},
 134: {'dmg': 0,
       'id': 2852,
       'maxSize': 64,
       'name': 'powerconverters.ic2.lv.consumer.name',
       'qty': 1,
       'rawName': 'powerconverters.ic2.lv.consumer'},
 135: {'dmg': 0,
       'id': 3123,
       'maxSize': 64,
       'name': 'tile.mfr.rubberwood.leaves.name',
       'qty': 116,
       'rawName': 'tile.mfr.rubberwood.leaves'},
 136: {'dmg': 0,
       'id': 3124,
       'maxSize': 64,
       'name': 'tile.mfr.rubberwood.sapling.name',
       'qty': 2,
       'rawName': 'tile.mfr.rubberwood.sapling'},
 137: {'dmg': 0,
       'id': 3237,
       'maxSize': 64,
       'name': 'Congealed Blue Slime',
       'qty': 8,
       'rawName': 'block.slime.congealed.blue'},
 138: {'dmg': 0,
       'id': 3240,
       'maxSize': 64,
       'name': 'Slimy Leaves',
       'qty': 5,
       'rawName': 'block.slime.leaves.blue'},
 139: {'dmg': 0,
       'id': 3767,
       'maxSize': 64,
       'name': 'tile.atomicscience:oreUranium.name',
       'qty': 56,
       'rawName': 'tile.atomicscience:oreuranium'},
 140: {'dmg': 0,
       'id': 4069,
       'maxSize': 64,
       'name': 'tile.extrabiomes.sapling.umber.name',
       'qty': 75,
       'rawName': 'tile.extrabiomes.sapling.umber'},
 141: {'dmg': 0,
       'id': 4076,
       'maxSize': 64,
       'name': 'tile.extrabiomes.leaves.umber.name',
       'qty': 44,
       'rawName': 'tile.extrabiomes.leaves.umber'},
 142: {'dmg': 0,
       'id': 4082,
       'maxSize': 64,
       'name': 'tile.extrabiomes.leafpile.name',
       'qty': 9,
       'rawName': 'tile.extrabiomes.leafpile'},
 143: {'dmg': 0,
       'id': 4095,
       'maxSize': 64,
       'name': 'AppEng.Blocks.ExportBusFuzzy.name',
       'qty': 1,
       'rawName': 'appeng.blocks.exportbusfuzzy'},
 144: {'dmg': 0,
       'id': 4157,
       'maxSize': 64,
       'name': 'item.icbm:sulfur.name',
       'qty': 1236,
       'rawName': 'item.icbm:sulfur'},
 145: {'dmg': 0,
       'id': 5259,
       'maxSize': 64,
       'name': 'Copper Ingot',
       'qty': 322,
       'rawName': 'item.ingotcopper'},
 146: {'dmg': 0,
       'id': 5260,
       'maxSize': 1,
       'name': 'item.glass.name',
       'qty': 2,
       'rawName': 'item.glass'},
 147: {'dmg': 0,
       'id': 5262,
       'maxSize': 1,
       'name': 'item.lapis.name',
       'qty': 1,
       'rawName': 'item.lapis'},
 148: {'dmg': 0,
       'id': 5264,
       'maxSize': 1,
       'name': 'item.aqueous.name',
       'qty': 1,
       'rawName': 'item.aqueous'},
 149: {'dmg': 0,
       'id': 6259,
       'maxSize': 64,
       'name': 'item.forceShard.name',
       'qty': 2,
       'rawName': 'item.forceshard'},
 150: {'dmg': 0,
       'id': 6288,
       'maxSize': 1,
       'name': 'item.forceBucket.name',
       'qty': 2,
       'rawName': 'item.forcebucket'},
 151: {'dmg': 0,
       'id': 6295,
       'maxSize': 1,
       'name': 'item.forceMitts.name',
       'qty': 3,
       'rawName': 'item.forcemitts'},
 152: {'dmg': 0,
       'id': 6299,
       'maxSize': 64,
       'name': 'item.itemTear.name',
       'qty': 1,
       'rawName': 'item.itemtear'},
 153: {'dmg': 0,
       'id': 6300,
       'maxSize': 64,
       'name': 'item.itemClaw.name',
       'qty': 3,
       'rawName': 'item.itemclaw'},
 154: {'dmg': 0,
       'id': 6309,
       'maxSize': 64,
       'name': 'item.gemForce.name',
       'qty': 161,
       'rawName': 'item.gemforce'},
 155: {'dmg': 0,
       'id': 6625,
       'maxSize': 64,
       'name': 'item.quantumdust.name',
       'qty': 258,
       'rawName': 'item.quantumdust'},
 156: {'dmg': 0,
       'id': 7004,
       'maxSize': 1,
       'name': 'item.blueStone.name',
       'qty': 1,
       'rawName': 'item.bluestone'},
 157: {'dmg': 0,
       'id': 7100,
       'maxSize': 1,
       'name': 'Bone',
       'qty': 2,
       'rawName': 'item.bone'},
 158: {'dmg': 0,
       'id': 7782,
       'maxSize': 64,
       'name': 'railcraft.dust.obsidian.name',
       'qty': 1,
       'rawName': 'railcraft.dust.obsidian'},
 159: {'dmg': 0,
       'id': 7792,
       'maxSize': 64,
       'name': 'railcraft.ingot.steel.name',
       'qty': 128,
       'rawName': 'railcraft.ingot.steel'},
 160: {'dmg': 0,
       'id': 7811,
       'maxSize': 1,
       'name': 'item.railcraft.tool.crowbar.name',
       'qty': 1,
       'rawName': 'item.railcraft.tool.crowbar'},
 161: {'dmg': 0,
       'id': 7817,
       'maxSize': 1,
       'name': 'item.railcraft.tool.steel.pickaxe.name',
       'qty': 1,
       'rawName': 'item.railcraft.tool.steel.pickaxe'},
 162: {'dmg': 0,
       'id': 7819,
       'maxSize': 1,
       'name': 'item.railcraft.tool.steel.sword.name',
       'qty': 1,
       'rawName': 'item.railcraft.tool.steel.sword'},
 163: {'dmg': 0,
       'id': 7822,
       'maxSize': 1,
       'name': 'item.railcraft.tool.steel.shears.name',
       'qty': 1,
       'rawName': 'item.railcraft.tool.steel.shears'},
 164: {'dmg': 0,
       'id': 8366,
       'maxSize': 64,
       'name': 'item.enderIO:itemMJReader.name',
       'qty': 1,
       'rawName': 'item.enderio:itemmjreader'},
 165: {'dmg': 0,
       'id': 8369,
       'maxSize': 64,
       'name': 'item.enderIO:itemPowderIngot.powderCoal.name',
       'qty': 711,
       'rawName': 'item.enderio:itempowderingot.powdercoal'},
 166: {'dmg': 0,
       'id': 9258,
       'maxSize': 1,
       'name': 'Pocket Crafting Table',
       'qty': 1,
       'rawName': 'item.factorization:tool/pocket_crafting_table'},
 167: {'dmg': 0,
       'id': 9299,
       'maxSize': 1,
       'name': 'Logic Matrix Programmer',
       'qty': 2,
       'rawName': 'item.factorization:tool/matrix_programmer'},
 168: {'dmg': 0,
       'id': 9501,
       'maxSize': 64,
       'name': 'AppEng.Materials.ConversionMatrix.name',
       'qty': 5,
       'rawName': 'appeng.materials.conversionmatrix'},
 169: {'dmg': 0,
       'id': 10558,
       'maxSize': 64,
       'name': 'item.PipeItemsInsertion',
       'qty': 1,
       'rawName': 'item.pipeitemsinsertion'},
 170: {'dmg': 0,
       'id': 12303,
       'maxSize': 1,
       'name': 'item.mfr.safarinet.singleuse.name',
       'qty': 1,
       'rawName': 'item.mfr.safarinet.singleuse'},
 171: {'dmg': 0,
       'id': 12659,
       'maxSize': 64,
       'name': 'Barley Seeds',
       'qty': 12,
       'rawName': 'item.barley.seed'},
 172: {'dmg': 0,
       'id': 13369,
       'maxSize': 1,
       'name': 'Soldering Iron',
       'qty': 1,
       'rawName': 'item.solderingiron'},
 173: {'dmg': 0,
       'id': 14274,
       'maxSize': 64,
       'name': 'Materials and You',
       'qty': 1,
       'rawName': 'item.tconstruct.manual.beginner'},
 174: {'dmg': 0,
       'id': 14362,
       'maxSize': 1,
       'name': 'Wooden Helmet',
       'qty': 1,
       'rawName': 'item.tconstruct.helmetwood'},
 175: {'dmg': 0,
       'id': 17069,
       'maxSize': 64,
       'name': 'item.PipeItemsCobblestone',
       'qty': 242,
       'rawName': 'item.pipeitemscobblestone'},
 176: {'dmg': 0,
       'id': 17070,
       'maxSize': 64,
       'name': 'item.PipeItemsDiamond',
       'qty': 8,
       'rawName': 'item.pipeitemsdiamond'},
 177: {'dmg': 0,
       'id': 17072,
       'maxSize': 64,
       'name': 'item.PipeItemsGold',
       'qty': 2,
       'rawName': 'item.pipeitemsgold'},
 178: {'dmg': 0,
       'id': 17076,
       'maxSize': 64,
       'name': 'item.PipeItemsStone',
       'qty': 37,
       'rawName': 'item.pipeitemsstone'},
 179: {'dmg': 0,
       'id': 17077,
       'maxSize': 64,
       'name': 'item.PipeItemsVoid',
       'qty': 8,
       'rawName': 'item.pipeitemsvoid'},
 180: {'dmg': 0,
       'id': 17078,
       'maxSize': 64,
       'name': 'item.PipeItemsWood',
       'qty': 7,
       'rawName': 'item.pipeitemswood'},
 181: {'dmg': 0,
       'id': 17088,
       'maxSize': 64,
       'name': 'item.PipePowerStone',
       'qty': 161,
       'rawName': 'item.pipepowerstone'},
 182: {'dmg': 0,
       'id': 17089,
       'maxSize': 64,
       'name': 'item.PipePowerWood',
       'qty': 12,
       'rawName': 'item.pipepowerwood'},
 183: {'dmg': 0,
       'id': 17091,
       'maxSize': 64,
       'name': 'item.pipeWaterproof',
       'qty': 10,
       'rawName': 'item.pipewaterproof'},
 184: {'dmg': 0,
       'id': 17095,
       'maxSize': 64,
       'name': 'item.woodenGearItem',
       'qty': 79,
       'rawName': 'item.woodengearitem'},
 185: {'dmg': 0,
       'id': 19438,
       'maxSize': 64,
       'name': 'item.PipeFluidsStone',
       'qty': 7,
       'rawName': 'item.pipefluidsstone'},
 186: {'dmg': 0,
       'id': 19457,
       'maxSize': 64,
       'name': 'item.PipePowerCobblestone',
       'qty': 2,
       'rawName': 'item.pipepowercobblestone'},
 187: {'dmg': 0,
       'id': 20374,
       'maxSize': 64,
       'name': 'Vinteum Dust',
       'qty': 278,
       'rawName': 'item.arsmagica2:itemore'},
 188: {'dmg': 0,
       'id': 21345,
       'maxSize': 1,
       'name': 'Flippers',
       'qty': 1,
       'rawName': 'item.bop.flippers'},
 189: {'dmg': 0,
       'id': 25258,
       'maxSize': 1,
       'name': 'Thaumonomicon',
       'qty': 1,
       'rawName': 'item.itemthaumonomicon'},
 190: {'dmg': 0,
       'id': 25363,
       'maxSize': 64,
       'name': 'Air Shard',
       'qty': 50,
       'rawName': 'item.itemshard.0'},
 191: {'dmg': 0,
       'id': 26106,
       'maxSize': 1,
       'name': 'item.frameOblivion.name',
       'qty': 1,
       'rawName': 'item.frameoblivion'},
 192: {'dmg': 0,
       'id': 27446,
       'maxSize': 1,
       'name': 'item.GT_Spray_Hydration.name',
       'qty': 1,
       'rawName': 'item.gt_spray_hydration'},
 193: {'dmg': 0,
       'id': 30040,
       'maxSize': 1,
       'name': 'ic2.itemToolForgeHammer',
       'qty': 1,
       'rawName': 'ic2.itemtoolforgehammer'},
 194: {'dmg': 0,
       'id': 30067,
       'maxSize': 64,
       'name': 'ic2.itemIngotCopper',
       'qty': 7432,
       'rawName': 'ic2.itemingotcopper'},
 195: {'dmg': 0,
       'id': 30128,
       'maxSize': 64,
       'name': 'ic2.itemOreIridium',
       'qty': 5,
       'rawName': 'ic2.itemoreiridium'},
 196: {'dmg': 0,
       'id': 30150,
       'maxSize': 64,
       'name': 'ic2.itemPartCarbonPlate',
       'qty': 25,
       'rawName': 'ic2.itempartcarbonplate'},
 197: {'dmg': 0,
       'id': 30182,
       'maxSize': 1,
       'name': 'ic2.itemToolMEter',
       'qty': 1,
       'rawName': 'ic2.itemtoolmeter'},
 198: {'dmg': 0,
       'id': 30184,
       'maxSize': 64,
       'name': 'ic2.itemCable',
       'qty': 146,
       'rawName': 'ic2.itemcable'},
 199: {'dmg': 0,
       'id': 30187,
       'maxSize': 64,
       'name': 'ic2.itemPartAlloy',
       'qty': 22,
       'rawName': 'ic2.itempartalloy'},
 200: {'dmg': 0,
       'id': 30189,
       'maxSize': 64,
       'name': 'ic2.itemScrap',
       'qty': 8382,
       'rawName': 'ic2.itemscrap'},
 201: {'dmg': 0,
       'id': 30191,
       'maxSize': 64,
       'name': 'ic2.itemPartCircuit',
       'qty': 62,
       'rawName': 'ic2.itempartcircuit'},
 202: {'dmg': 0,
       'id': 30193,
       'maxSize': 1,
       'name': 'ic2.itemArmorBronzeLegs',
       'qty': 1,
       'rawName': 'ic2.itemarmorbronzelegs'},
 203: {'dmg': 0,
       'id': 30195,
       'maxSize': 1,
       'name': 'ic2.itemArmorBronzeHelmet',
       'qty': 1,
       'rawName': 'ic2.itemarmorbronzehelmet'},
 204: {'dmg': 0,
       'id': 30206,
       'maxSize': 1,
       'name': 'ic2.reactorCoolantSimple',
       'qty': 97,
       'rawName': 'ic2.reactorcoolantsimple'},
 205: {'dmg': 0,
       'id': 30211,
       'maxSize': 1,
       'name': 'ic2.itemArmorRubBoots',
       'qty': 1,
       'rawName': 'ic2.itemarmorrubboots'},
 206: {'dmg': 0,
       'id': 30216,
       'maxSize': 64,
       'name': 'ic2.itemRubber',
       'qty': 412,
       'rawName': 'ic2.itemrubber'},
 207: {'dmg': 0,
       'id': 30217,
       'maxSize': 64,
       'name': 'ic2.itemHarz',
       'qty': 11,
       'rawName': 'ic2.itemharz'},
 208: {'dmg': 0,
       'id': 30241,
       'maxSize': 1,
       'name': 'ic2.itemBatCrystal',
       'qty': 8,
       'rawName': 'ic2.itembatcrystal'},
 209: {'dmg': 0,
       'id': 31983,
       'maxSize': 64,
       'name': 'Tin Gear',
       'qty': 1,
       'rawName': 'item.geartin'},
 210: {'dmg': 0,
       'id': 31992,
       'maxSize': 64,
       'name': 'Bronze Ingot',
       'qty': 129,
       'rawName': 'item.ingotbronze'},
 211: {'dmg': 1,
       'id': 259,
       'maxSize': 1,
       'name': 'Flint and Steel',
       'qty': 1,
       'rawName': 'item.flintandsteel'},
 212: {'dmg': 1,
       'id': 645,
       'maxSize': 64,
       'name': 'tile.BlockMetaID_Ore.Galena_Ore.name',
       'qty': 67,
       'rawName': 'tile.blockmetaid_ore.galena_ore'},
 213: {'dmg': 1,
       'id': 790,
       'maxSize': 64,
       'name': 'Chimerite Ore',
       'qty': 79,
       'rawName': 'tile.arsmagica2:ores.1'},
 214: {'dmg': 1,
       'id': 861,
       'maxSize': 64,
       'name': 'AppEng.Blocks.ImportBusPrecision.name',
       'qty': 1,
       'rawName': 'appeng.blocks.importbusprecision'},
 215: {'dmg': 1,
       'id': 1471,
       'maxSize': 64,
       'name': 'Part Builder',
       'qty': 1,
       'rawName': 'toolstation.parts'},
 216: {'dmg': 1,
       'id': 2130,
       'maxSize': 64,
       'name': 'Sapphire Ore',
       'qty': 9,
       'rawName': 'tile.projectred.exploration.ore.oresapphire'},
 217: {'dmg': 1,
       'id': 2226,
       'maxSize': 64,
       'name': 'tile.extrabiomes.leaves.japanese_maple.name',
       'qty': 4,
       'rawName': 'tile.extrabiomes.leaves.japanese_maple'},
 218: {'dmg': 1,
       'id': 2231,
       'maxSize': 64,
       'name': 'tile.extrabiomes.newlog.1.name',
       'qty': 694,
       'rawName': 'tile.extrabiomes.newlog.1'},
 219: {'dmg': 1,
       'id': 2851,
       'maxSize': 64,
       'name': 'powerconverters.bc.producer.name',
       'qty': 1,
       'rawName': 'powerconverters.bc.producer'},
 220: {'dmg': 1,
       'id': 2852,
       'maxSize': 64,
       'name': 'powerconverters.ic2.lv.producer.name',
       'qty': 1,
       'rawName': 'powerconverters.ic2.lv.producer'},
 221: {'dmg': 1,
       'id': 3101,
       'maxSize': 64,
       'name': 'Rock Hive',
       'qty': 14,
       'rawName': 'tile.hive'},
 222: {'dmg': 1,
       'id': 3237,
       'maxSize': 64,
       'name': 'Congealed Green Slime',
       'qty': 5,
       'rawName': 'block.slime.congealed.green'},
 223: {'dmg': 1,
       'id': 3257,
       'maxSize': 64,
       'name': 'Blueberry Bush',
       'qty': 6,
       'rawName': 'block.blueberrybush'},
 224: {'dmg': 1,
       'id': 4069,
       'maxSize': 64,
       'name': 'tile.extrabiomes.sapling.goldenrod.name',
       'qty': 33,
       'rawName': 'tile.extrabiomes.sapling.goldenrod'},
 225: {'dmg': 1,
       'id': 4076,
       'maxSize': 64,
       'name': 'tile.extrabiomes.leaves.goldenrod.name',
       'qty': 19,
       'rawName': 'tile.extrabiomes.leaves.goldenrod'},
 226: {'dmg': 1,
       'id': 7782,
       'maxSize': 64,
       'name': 'railcraft.dust.sulfur.name',
       'qty': 478,
       'rawName': 'railcraft.dust.sulfur'},
 227: {'dmg': 1,
       'id': 7793,
       'maxSize': 64,
       'name': 'railcraft.nugget.steel.name',
       'qty': 8,
       'rawName': 'railcraft.nugget.steel'},
 228: {'dmg': 1,
       'id': 7796,
       'maxSize': 64,
       'name': 'railcraft.part.plate.steel.name',
       'qty': 9,
       'rawName': 'railcraft.part.plate.steel'},
 229: {'dmg': 1,
       'id': 12659,
       'maxSize': 64,
       'name': 'Cotton Seeds',
       'qty': 11,
       'rawName': 'item.cotton.seed'},
 230: {'dmg': 1,
       'id': 13284,
       'maxSize': 1,
       'name': 'Scoop',
       'qty': 1,
       'rawName': 'item.scoop'},
 231: {'dmg': 1,
       'id': 14274,
       'maxSize': 64,
       'name': 'Materials and You',
       'qty': 2,
       'rawName': 'item.tconstruct.manual.toolstation'},
 232: {'dmg': 1,
       'id': 14300,
       'maxSize': 64,
       'name': 'Stone Large Plate',
       'qty': 1,
       'rawName': 'item.tconstruct.largeplate.stone'},
 233: {'dmg': 1,
       'id': 21266,
       'maxSize': 64,
       'name': 'Pile of Ashes',
       'qty': 11,
       'rawName': 'item.bop.miscitems.ash'},
 234: {'dmg': 1,
       'id': 25356,
       'maxSize': 64,
       'name': 'Nitor',
       'qty': 1,
       'rawName': 'item.itemresource.1'},
 235: {'dmg': 1,
       'id': 25363,
       'maxSize': 64,
       'name': 'Fire Shard',
       'qty': 91,
       'rawName': 'item.itemshard.1'},
 236: {'dmg': 1,
       'id': 29925,
       'maxSize': 64,
       'name': 'item.waterwheelitem.1',
       'qty': 1,
       'rawName': 'item.waterwheelitem'},
 237: {'dmg': 1,
       'id': 30037,
       'maxSize': 64,
       'name': 'ic2.itemCasingTin',
       'qty': 1106,
       'rawName': 'ic2.itemcasingtin'},
 238: {'dmg': 1,
       'id': 30067,
       'maxSize': 64,
       'name': 'ic2.itemIngotTin',
       'qty': 3926,
       'rawName': 'ic2.itemingottin'},
 239: {'dmg': 1,
       'id': 30184,
       'maxSize': 64,
       'name': 'ic2.itemCableO',
       'qty': 104,
       'rawName': 'ic2.itemcableo'},
 240: {'dmg': 1,
       'id': 30221,
       'maxSize': 64,
       'name': 'ic2.itemTinCanFilled',
       'qty': 1,
       'rawName': 'ic2.itemtincanfilled'},
 241: {'dmg': 2,
       'id': 645,
       'maxSize': 64,
       'name': 'tile.BlockMetaID_Ore.Iridium_Ore.name',
       'qty': 1,
       'rawName': 'tile.blockmetaid_ore.iridium_ore'},
 242: {'dmg': 2,
       'id': 860,
       'maxSize': 64,
       'name': 'AppEng.Blocks.Controller.name',
       'qty': 1,
       'rawName': 'appeng.blocks.controller'},
 243: {'dmg': 2,
       'id': 1475,
       'maxSize': 64,
       'name': 'Ardite Ore',
       'qty': 5,
       'rawName': 'metalore.ardite'},
 244: {'dmg': 2,
       'id': 1485,
       'maxSize': 64,
       'name': 'Copper Oreberry Bush',
       'qty': 9,
       'rawName': 'block.oreberry.copper'},
 245: {'dmg': 2,
       'id': 2130,
       'maxSize': 64,
       'name': 'Peridot Ore',
       'qty': 3,
       'rawName': 'tile.projectred.exploration.ore.oreperidot'},
 246: {'dmg': 2,
       'id': 2231,
       'maxSize': 64,
       'name': 'tile.extrabiomes.newlog.2.name',
       'qty': 1064,
       'rawName': 'tile.extrabiomes.newlog.2'},
 247: {'dmg': 2,
       'id': 2852,
       'maxSize': 64,
       'name': 'powerconverters.ic2.mv.consumer.name',
       'qty': 1,
       'rawName': 'powerconverters.ic2.mv.consumer'},
 248: {'dmg': 2,
       'id': 3257,
       'maxSize': 64,
       'name': 'Blackberry Bush',
       'qty': 45,
       'rawName': 'block.blackberrybush'},
 249: {'dmg': 2,
       'id': 3529,
       'maxSize': 64,
       'name': 'tile.extrabiomes.flower.2.name',
       'qty': 9,
       'rawName': 'tile.extrabiomes.flower.2'},
 250: {'dmg': 2,
       'id': 4069,
       'maxSize': 64,
       'name': 'tile.extrabiomes.sapling.vermillion.name',
       'qty': 40,
       'rawName': 'tile.extrabiomes.sapling.vermillion'},
 251: {'dmg': 2,
       'id': 4076,
       'maxSize': 64,
       'name': 'tile.extrabiomes.leaves.vermillion.name',
       'qty': 56,
       'rawName': 'tile.extrabiomes.leaves.vermillion'},
 252: {'dmg': 2,
       'id': 12660,
       'maxSize': 64,
       'name': 'Wheat Flour',
       'qty': 1,
       'rawName': 'item.wheat.flour'},
 253: {'dmg': 2,
       'id': 14274,
       'maxSize': 64,
       'name': 'Mighty Smelting',
       'qty': 1,
       'rawName': 'item.tconstruct.manual.smeltery'},
 254: {'dmg': 2,
       'id': 14276,
       'maxSize': 64,
       'name': 'Seared Brick',
       'qty': 4,
       'rawName': 'item.tconstruct.materials.searedbrick'},
 255: {'dmg': 2,
       'id': 25356,
       'maxSize': 64,
       'name': 'Thaumium Ingot',
       'qty': 1,
       'rawName': 'item.itemresource.2'},
 256: {'dmg': 2,
       'id': 25363,
       'maxSize': 64,
       'name': 'Water Shard',
       'qty': 65,
       'rawName': 'item.itemshard.2'},
 257: {'dmg': 2,
       'id': 30037,
       'maxSize': 64,
       'name': 'ic2.itemCasingBronze',
       'qty': 28,
       'rawName': 'ic2.itemcasingbronze'},
 258: {'dmg': 2,
       'id': 30125,
       'maxSize': 4,
       'name': 'ic2.energyStorageUpgrade',
       'qty': 8,
       'rawName': 'ic2.energystorageupgrade'},
 259: {'dmg': 2,
       'id': 30184,
       'maxSize': 64,
       'name': 'ic2.itemGoldCable',
       'qty': 47,
       'rawName': 'ic2.itemgoldcable'},
 260: {'dmg': 3,
       'id': 291,
       'maxSize': 1,
       'name': 'Stone Hoe',
       'qty': 1,
       'rawName': 'item.hoestone'},
 261: {'dmg': 3,
       'id': 608,
       'maxSize': 64,
       'name': 'ic2.blockTransformerLV',
       'qty': 55,
       'rawName': 'ic2.blocktransformerlv'},
 262: {'dmg': 3,
       'id': 1485,
       'maxSize': 64,
       'name': 'Tin Oreberry Bush',
       'qty': 1,
       'rawName': 'block.oreberry.tin'},
 263: {'dmg': 3,
       'id': 2852,
       'maxSize': 64,
       'name': 'powerconverters.ic2.mv.producer.name',
       'qty': 1,
       'rawName': 'powerconverters.ic2.mv.producer'},
 264: {'dmg': 3,
       'id': 4069,
       'maxSize': 64,
       'name': 'tile.extrabiomes.sapling.citrine.name',
       'qty': 26,
       'rawName': 'tile.extrabiomes.sapling.citrine'},
 265: {'dmg': 3,
       'id': 4076,
       'maxSize': 64,
       'name': 'tile.extrabiomes.leaves.citrine.name',
       'qty': 19,
       'rawName': 'tile.extrabiomes.leaves.citrine'},
 266: {'dmg': 3,
       'id': 4078,
       'maxSize': 64,
       'name': 'tile.extrabiomes.log.3.name',
       'qty': 12,
       'rawName': 'tile.extrabiomes.log.3'},
 267: {'dmg': 3,
       'id': 4095,
       'maxSize': 64,
       'name': 'AppEng.Blocks.ImportBus.name',
       'qty': 4,
       'rawName': 'appeng.blocks.importbus'},
 268: {'dmg': 3,
       'id': 4371,
       'maxSize': 1,
       'name': 'AppEng.Tools.QuartzCuttingKnife.name',
       'qty': 1,
       'rawName': 'appeng.tools.quartzcuttingknife'},
 269: {'dmg': 3,
       'id': 7782,
       'maxSize': 64,
       'name': 'railcraft.dust.charcoal.name',
       'qty': 54,
       'rawName': 'railcraft.dust.charcoal'},
 270: {'dmg': 3,
       'id': 12660,
       'maxSize': 64,
       'name': 'Cotton',
       'qty': 1,
       'rawName': 'item.cotton.plant'},
 271: {'dmg': 3,
       'id': 14360,
       'maxSize': 64,
       'name': 'Tin Oreberry',
       'qty': 1,
       'rawName': 'item.oreberry.tin'},
 272: {'dmg': 3,
       'id': 25356,
       'maxSize': 64,
       'name': 'Quicksilver',
       'qty': 107,
       'rawName': 'item.itemresource.3'},
 273: {'dmg': 3,
       'id': 25363,
       'maxSize': 64,
       'name': 'Earth Shard',
       'qty': 281,
       'rawName': 'item.itemshard.3'},
 274: {'dmg': 3,
       'id': 27361,
       'maxSize': 64,
       'name': 'item.GT_Dusts.3.name',
       'qty': 93,
       'rawName': 'item.gt_dusts.3'},
 275: {'dmg': 3,
       'id': 30067,
       'maxSize': 64,
       'name': 'ic2.itemIngotAdvIron',
       'qty': 58,
       'rawName': 'ic2.itemingotadviron'},
 276: {'dmg': 3,
       'id': 30184,
       'maxSize': 64,
       'name': 'ic2.itemGoldCableI',
       'qty': 1,
       'rawName': 'ic2.itemgoldcablei'},
 277: {'dmg': 3,
       'id': 31971,
       'maxSize': 64,
       'name': 'item.GT_TinyDusts.3.name',
       'qty': 144,
       'rawName': 'item.gt_tinydusts.3'},
 278: {'dmg': 4,
       'id': 351,
       'maxSize': 64,
       'name': 'Lapis Lazuli',
       'qty': 328,
       'rawName': 'item.dyepowder.blue'},
 279: {'dmg': 4,
       'id': 359,
       'maxSize': 1,
       'name': 'Shears',
       'qty': 1,
       'rawName': 'item.shears'},
 280: {'dmg': 4,
       'id': 611,
       'maxSize': 64,
       'name': 'ic2.blockWindGenerator',
       'qty': 3,
       'rawName': 'ic2.blockwindgenerator'},
 281: {'dmg': 4,
       'id': 1478,
       'maxSize': 64,
       'name': 'Block of Bronze',
       'qty': 15,
       'rawName': 'storagemetals.bronze'},
 282: {'dmg': 4,
       'id': 1921,
       'maxSize': 64,
       'name': 'Blue Hydrangea',
       'qty': 1,
       'rawName': 'tile.bop.flowers.hydrangea'},
 283: {'dmg': 4,
       'id': 3529,
       'maxSize': 64,
       'name': 'tile.extrabiomes.flower.4.name',
       'qty': 2,
       'rawName': 'tile.extrabiomes.flower.4'},
 284: {'dmg': 4,
       'id': 20374,
       'maxSize': 64,
       'name': 'Chimerite',
       'qty': 528,
       'rawName': 'item.arsmagica2:itemore'},
 285: {'dmg': 4,
       'id': 25363,
       'maxSize': 64,
       'name': 'Order Shard',
       'qty': 92,
       'rawName': 'item.itemshard.4'},
 286: {'dmg': 4,
       'id': 27361,
       'maxSize': 64,
       'name': 'item.GT_Dusts.4.name',
       'qty': 1,
       'rawName': 'item.gt_dusts.4'},
 287: {'dmg': 4,
       'id': 29914,
       'maxSize': 64,
       'name': 'item.ammoitem.4',
       'qty': 5,
       'rawName': 'item.ammoitem'},
 288: {'dmg': 4,
       'id': 30064,
       'maxSize': 64,
       'name': 'ic2.itemCrushedUranOre',
       'qty': 68,
       'rawName': 'ic2.itemcrusheduranore'},
 289: {'dmg': 5,
       'id': 645,
       'maxSize': 64,
       'name': 'tile.BlockMetaID_Ore.Bauxite_Ore.name',
       'qty': 409,
       'rawName': 'tile.blockmetaid_ore.bauxite_ore'},
 290: {'dmg': 5,
       'id': 1471,
       'maxSize': 64,
       'name': 'Pattern Chest',
       'qty': 1,
       'rawName': 'toolstation.patternchest'},
 291: {'dmg': 5,
       'id': 1475,
       'maxSize': 64,
       'name': 'Aluminum Ore',
       'qty': 67,
       'rawName': 'metalore.aluminum'},
 292: {'dmg': 5,
       'id': 1920,
       'maxSize': 64,
       'name': 'Thorns',
       'qty': 12,
       'rawName': 'tile.bop.plants.thorn'},
 293: {'dmg': 5,
       'id': 20374,
       'maxSize': 64,
       'name': 'Blue Topaz',
       'qty': 395,
       'rawName': 'item.arsmagica2:itemore'},
 294: {'dmg': 5,
       'id': 25356,
       'maxSize': 64,
       'name': 'Zombie Brain',
       'qty': 25,
       'rawName': 'item.itemresource.5'},
 295: {'dmg': 5,
       'id': 25363,
       'maxSize': 64,
       'name': 'Entropy Shard',
       'qty': 82,
       'rawName': 'item.itemshard.5'},
 296: {'dmg': 5,
       'id': 30067,
       'maxSize': 64,
       'name': 'ic2.itemIngotLead',
       'qty': 607,
       'rawName': 'ic2.itemingotlead'},
 297: {'dmg': 5,
       'id': 30184,
       'maxSize': 64,
       'name': 'ic2.itemIronCable',
       'qty': 8,
       'rawName': 'ic2.itemironcable'},
 298: {'dmg': 5,
       'id': 30237,
       'maxSize': 64,
       'name': 'ic2.itemCellAir',
       'qty': 2,
       'rawName': 'ic2.itemcellair'},
 299: {'dmg': 6,
       'id': 617,
       'maxSize': 64,
       'name': 'ic2.blockCanner',
       'qty': 1,
       'rawName': 'ic2.blockcanner'},
 300: {'dmg': 6,
       'id': 1478,
       'maxSize': 64,
       'name': 'Block of Aluminum',
       'qty': 1,
       'rawName': 'storagemetals.aluminum'},
 301: {'dmg': 6,
       'id': 3520,
       'maxSize': 64,
       'name': 'tile.extrabiomes.planks.6.name',
       'qty': 42,
       'rawName': 'tile.extrabiomes.planks.6'},
 302: {'dmg': 6,
       'id': 3529,
       'maxSize': 64,
       'name': 'tile.extrabiomes.flower.6.name',
       'qty': 6,
       'rawName': 'tile.extrabiomes.flower.6'},
 303: {'dmg': 6,
       'id': 9501,
       'maxSize': 64,
       'name': 'AppEng.Materials.QuartzCrystal.name',
       'qty': 35,
       'rawName': 'appeng.materials.quartzcrystal'},
 304: {'dmg': 6,
       'id': 14300,
       'maxSize': 64,
       'name': 'Obsidian Large Plate',
       'qty': 1,
       'rawName': 'item.tconstruct.largeplate.obsidian'},
 305: {'dmg': 6,
       'id': 25356,
       'maxSize': 64,
       'name': 'Amber',
       'qty': 302,
       'rawName': 'item.itemresource.6'},
 306: {'dmg': 6,
       'id': 30066,
       'maxSize': 64,
       'name': 'ic2.itemDustSilver',
       'qty': 3,
       'rawName': 'ic2.itemdustsilver'},
 307: {'dmg': 6,
       'id': 30067,
       'maxSize': 64,
       'name': 'ic2.itemIngotSilver',
       'qty': 735,
       'rawName': 'ic2.itemingotsilver'},
 308: {'dmg': 7,
       'id': 283,
       'maxSize': 1,
       'name': 'Golden Sword',
       'qty': 1,
       'rawName': 'item.swordgold'},
 309: {'dmg': 7,
       'id': 645,
       'maxSize': 64,
       'name': 'tile.BlockMetaID_Ore.Cinnabar_Ore.name',
       'qty': 5,
       'rawName': 'tile.blockmetaid_ore.cinnabar_ore'},
 310: {'dmg': 7,
       'id': 3520,
       'maxSize': 64,
       'name': 'tile.extrabiomes.planks.7.name',
       'qty': 676,
       'rawName': 'tile.extrabiomes.planks.7'},
 311: {'dmg': 7,
       'id': 9501,
       'maxSize': 64,
       'name': 'AppEng.Materials.QuartzDust.name',
       'qty': 71,
       'rawName': 'appeng.materials.quartzdust'},
 312: {'dmg': 7,
       'id': 12660,
       'maxSize': 64,
       'name': 'Flamestring',
       'qty': 23,
       'rawName': 'item.string.flame'},
 313: {'dmg': 7,
       'id': 27361,
       'maxSize': 64,
       'name': 'item.GT_Dusts.7.name',
       'qty': 1,
       'rawName': 'item.gt_dusts.7'},
 314: {'dmg': 8,
       'id': 645,
       'maxSize': 64,
       'name': 'tile.BlockMetaID_Ore.Sphalerite_Ore.name',
       'qty': 22,
       'rawName': 'tile.blockmetaid_ore.sphalerite_ore'},
 315: {'dmg': 8,
       'id': 817,
       'maxSize': 64,
       'name': 'Witchwood Leaves',
       'qty': 361,
       'rawName': 'tile.arsmagica2:witchwoodleaves'},
 316: {'dmg': 8,
       'id': 860,
       'maxSize': 64,
       'name': 'AppEng.Blocks.Interface.name',
       'qty': 18,
       'rawName': 'appeng.blocks.interface'},
 317: {'dmg': 8,
       'id': 4076,
       'maxSize': 64,
       'name': 'tile.extrabiomes.leaves.umber.name',
       'qty': 909,
       'rawName': 'tile.extrabiomes.leaves.umber'},
 318: {'dmg': 8,
       'id': 14276,
       'maxSize': 64,
       'name': 'Necrotic Bone',
       'qty': 3,
       'rawName': 'item.tconstruct.materials.necroticbone'},
 319: {'dmg': 8,
       'id': 31971,
       'maxSize': 64,
       'name': 'item.GT_TinyDusts.8.name',
       'qty': 1088,
       'rawName': 'item.gt_tinydusts.8'},
 320: {'dmg': 9,
       'id': 4062,
       'maxSize': 64,
       'name': 'tile.BlockMetaID_Stone1.GT_Red_Granite_Cobble.name',
       'qty': 1136,
       'rawName': 'tile.blockmetaid_stone1.gt_red_granite_cobble'},
 321: {'dmg': 9,
       'id': 4076,
       'maxSize': 64,
       'name': 'tile.extrabiomes.leaves.goldenrod.name',
       'qty': 537,
       'rawName': 'tile.extrabiomes.leaves.goldenrod'},
 322: {'dmg': 9,
       'id': 25356,
       'maxSize': 64,
       'name': 'Knowledge Fragment',
       'qty': 3,
       'rawName': 'item.itemresource.9'},
 323: {'dmg': 9,
       'id': 30184,
       'maxSize': 64,
       'name': 'ic2.itemGlassCable',
       'qty': 19,
       'rawName': 'ic2.itemglasscable'},
 324: {'dmg': 10,
       'id': 1471,
       'maxSize': 64,
       'name': 'Stencil Table',
       'qty': 1,
       'rawName': 'toolstation.patternshaper'},
 325: {'dmg': 10,
       'id': 4076,
       'maxSize': 64,
       'name': 'tile.extrabiomes.leaves.vermillion.name',
       'qty': 1059,
       'rawName': 'tile.extrabiomes.leaves.vermillion'},
 326: {'dmg': 10,
       'id': 30184,
       'maxSize': 64,
       'name': 'ic2.itemTinCable',
       'qty': 4,
       'rawName': 'ic2.itemtincable'},
 327: {'dmg': 11,
       'id': 35,
       'maxSize': 64,
       'name': 'Blue Wool',
       'qty': 61,
       'rawName': 'tile.cloth.blue'},
 328: {'dmg': 11,
       'id': 351,
       'maxSize': 64,
       'name': 'Dandelion Yellow',
       'qty': 22,
       'rawName': 'item.dyepowder.yellow'},
 329: {'dmg': 11,
       'id': 14276,
       'maxSize': 64,
       'name': 'Aluminum Ingot',
       'qty': 5,
       'rawName': 'item.tconstruct.materials.aluminumingot'},
 330: {'dmg': 11,
       'id': 21266,
       'maxSize': 64,
       'name': 'Peridot',
       'qty': 20,
       'rawName': 'item.bop.miscitems.peridot'},
 331: {'dmg': 11,
       'id': 31973,
       'maxSize': 64,
       'name': 'item.GT_DirtyDusts.11.name',
       'qty': 32,
       'rawName': 'item.gt_dirtydusts.11'},
 332: {'dmg': 12,
       'id': 14276,
       'maxSize': 64,
       'name': 'Raw Aluminum',
       'qty': 72,
       'rawName': 'item.tconstruct.materials.rawaluminum'},
 333: {'dmg': 13,
       'id': 645,
       'maxSize': 64,
       'name': 'tile.BlockMetaID_Ore.Tetrahedrite_Ore.name',
       'qty': 1,
       'rawName': 'tile.blockmetaid_ore.tetrahedrite_ore'},
 334: {'dmg': 13,
       'id': 650,
       'maxSize': 64,
       'name': 'tile.BlockMetaID_Block.Standard_Machine_Casing.name',
       'qty': 2,
       'rawName': 'tile.blockmetaid_block.standard_machine_casing'},
 335: {'dmg': 13,
       'id': 4371,
       'maxSize': 1,
       'name': 'AppEng.Tools.QuartzCuttingKnife.name',
       'qty': 1,
       'rawName': 'appeng.tools.quartzcuttingknife'},
 336: {'dmg': 13,
       'id': 9501,
       'maxSize': 64,
       'name': 'AppEng.Materials.Silicon.name',
       'qty': 189,
       'rawName': 'appeng.materials.silicon'},
 337: {'dmg': 13,
       'id': 30184,
       'maxSize': 64,
       'name': 'ic2.itemTinCableI',
       'qty': 50,
       'rawName': 'ic2.itemtincablei'},
 338: {'dmg': 14,
       'id': 861,
       'maxSize': 64,
       'name': 'AppEng.Blocks.Cable.name',
       'qty': 60,
       'rawName': 'appeng.blocks.cable'},
 339: {'dmg': 14,
       'id': 1440,
       'maxSize': 64,
       'name': 'tile.netherores.ore.peridot.name',
       'qty': 2,
       'rawName': 'tile.netherores.ore.peridot'},
 340: {'dmg': 14,
       'id': 9501,
       'maxSize': 64,
       'name': 'AppEng.Materials.FluxQuartzDust.name',
       'qty': 52,
       'rawName': 'appeng.materials.fluxquartzdust'},
 341: {'dmg': 14,
       'id': 21266,
       'maxSize': 64,
       'name': 'Apatite',
       'qty': 2,
       'rawName': 'item.bop.miscitems.apatite'},
 342: {'dmg': 14,
       'id': 27361,
       'maxSize': 64,
       'name': 'item.GT_Dusts.14.name',
       'qty': 5,
       'rawName': 'item.gt_dusts.14'},
 343: {'dmg': 14,
       'id': 31973,
       'maxSize': 64,
       'name': 'item.GT_DirtyDusts.14.name',
       'qty': 184,
       'rawName': 'item.gt_dirtydusts.14'},
 344: {'dmg': 15,
       'id': 351,
       'maxSize': 64,
       'name': 'Bone Meal',
       'qty': 84,
       'rawName': 'item.dyepowder.white'},
 345: {'dmg': 0,
       'id': 387,
       'maxSize': 1,
       'name': 'GregTech Manual II',
       'qty': 1,
       'rawName': 'item.writtenbook'},
 346: {'dmg': 17,
       'id': 27402,
       'maxSize': 64,
       'name': 'item.GT_Materials.17.name',
       'qty': 158,
       'rawName': 'item.gt_materials.17'},
 347: {'dmg': 17,
       'id': 31973,
       'maxSize': 64,
       'name': 'item.GT_DirtyDusts.17.name',
       'qty': 1864,
       'rawName': 'item.gt_dirtydusts.17'},
 348: {'dmg': 18,
       'id': 27361,
       'maxSize': 64,
       'name': 'item.GT_Dusts.18.name',
       'qty': 4,
       'rawName': 'item.gt_dusts.18'},
 349: {'dmg': 19,
       'id': 14276,
       'maxSize': 64,
       'name': 'Iron Nugget',
       'qty': 41,
       'rawName': 'item.tconstruct.materials.ironnugget'},
 350: {'dmg': 20,
       'id': 14276,
       'maxSize': 64,
       'name': 'Copper Nugget',
       'qty': 3,
       'rawName': 'item.tconstruct.materials.coppernugget'},
 351: {'dmg': 22,
       'id': 9501,
       'maxSize': 64,
       'name': 'AppEng.Materials.QuartzDustNether.name',
       'qty': 48,
       'rawName': 'appeng.materials.quartzdustnether'},
 352: {'dmg': 22,
       'id': 14276,
       'maxSize': 64,
       'name': 'Aluminum Nugget',
       'qty': 55,
       'rawName': 'item.tconstruct.materials.aluminumnugget'},
 353: {'dmg': 23,
       'id': 27402,
       'maxSize': 64,
       'name': 'item.GT_Materials.23.name',
       'qty': 106,
       'rawName': 'item.gt_materials.23'},
 354: {'dmg': 26,
       'id': 27361,
       'maxSize': 64,
       'name': 'item.GT_Dusts.26.name',
       'qty': 1,
       'rawName': 'item.gt_dusts.26'},
 355: {'dmg': 26,
       'id': 27402,
       'maxSize': 64,
       'name': 'item.GT_Materials.26.name',
       'qty': 2,
       'rawName': 'item.gt_materials.26'},
 356: {'dmg': 28,
       'id': 27361,
       'maxSize': 64,
       'name': 'item.GT_Dusts.28.name',
       'qty': 96,
       'rawName': 'item.gt_dusts.28'},
 357: {'dmg': 32,
       'id': 27402,
       'maxSize': 64,
       'name': 'item.GT_Materials.32.name',
       'qty': 15,
       'rawName': 'item.gt_materials.32'},
 358: {'dmg': 34,
       'id': 27402,
       'maxSize': 64,
       'name': 'item.GT_Materials.34.name',
       'qty': 7,
       'rawName': 'item.gt_materials.34'},
 359: {'dmg': 35,
       'id': 27357,
       'maxSize': 64,
       'name': 'item.GT_Components.35.name',
       'qty': 3,
       'rawName': 'item.gt_components.35'},
 360: {'dmg': 37,
       'id': 31890,
       'maxSize': 64,
       'name': 'Ruby',
       'qty': 96,
       'rawName': 'item.projectred.core.part.gemruby'},
 361: {'dmg': 38,
       'id': 31890,
       'maxSize': 64,
       'name': 'Sapphire',
       'qty': 143,
       'rawName': 'item.projectred.core.part.gemsapphire'},
 362: {'dmg': 39,
       'id': 31890,
       'maxSize': 64,
       'name': 'Peridot',
       'qty': 216,
       'rawName': 'item.projectred.core.part.gemperidot'},
 363: {'dmg': 43,
       'id': 30040,
       'maxSize': 1,
       'name': 'ic2.itemToolForgeHammer',
       'qty': 1,
       'rawName': 'ic2.itemtoolforgehammer'},
 364: {'dmg': 44,
       'id': 27402,
       'maxSize': 64,
       'name': 'item.GT_Materials.44.name',
       'qty': 1,
       'rawName': 'item.gt_materials.44'},
 365: {'dmg': 44,
       'id': 31973,
       'maxSize': 64,
       'name': 'item.GT_DirtyDusts.44.name',
       'qty': 84,
       'rawName': 'item.gt_dirtydusts.44'},
 366: {'dmg': 49,
       'id': 4371,
       'maxSize': 1,
       'name': 'AppEng.Tools.QuartzCuttingKnife.name',
       'qty': 1,
       'rawName': 'appeng.tools.quartzcuttingknife'},
 367: {'dmg': 50,
       'id': 653,
       'maxSize': 64,
       'name': 'tile.BlockMetaID_Machine.GT_Macerator.name',
       'qty': 2,
       'rawName': 'tile.blockmetaid_machine.gt_macerator'},
 368: {'dmg': 52,
       'id': 314,
       'maxSize': 1,
       'name': 'Golden Helmet',
       'qty': 1,
       'rawName': 'item.helmetgold'},
 369: {'dmg': 54,
       'id': 27402,
       'maxSize': 64,
       'name': 'item.GT_Materials.54.name',
       'qty': 3,
       'rawName': 'item.gt_materials.54'},
 370: {'dmg': 66,
       'id': 27402,
       'maxSize': 64,
       'name': 'item.GT_Materials.66.name',
       'qty': 13,
       'rawName': 'item.gt_materials.66'},
 371: {'dmg': 68,
       'id': 27402,
       'maxSize': 64,
       'name': 'item.GT_Materials.68.name',
       'qty': 32,
       'rawName': 'item.gt_materials.68'},
 372: {'dmg': 1,
       'id': 14321,
       'maxSize': 1,
       'name': 'Dagger',
       'qty': 1,
       'rawName': 'item.infitool.dagger'},
 373: {'dmg': 80,
       'id': 31971,
       'maxSize': 64,
       'name': 'item.GT_TinyDusts.80.name',
       'qty': 80,
       'rawName': 'item.gt_tinydusts.80'},
 374: {'beeInfo': {'canSpawn': False,
                   'displayName': 'Rocky',
                   'generation': 0,
                   'hasEffect': False,
                   'health': 30,
                   'ident': 'extrabees.species.rock',
                   'isAlive': True,
                   'isAnalyzed': False,
                   'isIrregularMating': False,
                   'isNatural': True,
                   'isSecret': False,
                   'maxHealth': 30},
       'dmg': 0,
       'id': 13340,
       'maxSize': 64,
       'name': 'Rockybees.drone.adj.add bees.drone',
       'qty': 8,
       'rawName': 'item.beedronege'},
 375: {'dmg': 112,
       'id': 27469,
       'maxSize': 1,
       'name': 'item.GT_Wrench_Bronze.name',
       'qty': 1,
       'rawName': 'item.gt_wrench_bronze'},
 376: {'dmg': 0,
       'id': 387,
       'maxSize': 1,
       'name': 'Crop Dictionary V3.03a',
       'qty': 1,
       'rawName': 'item.writtenbook'},
 377: {'dmg': 149,
       'id': 7817,
       'maxSize': 1,
       'name': 'item.railcraft.tool.steel.pickaxe.name',
       'qty': 1,
       'rawName': 'item.railcraft.tool.steel.pickaxe'},
 378: {'dmg': 1,
       'id': 27470,
       'maxSize': 1,
       'name': 'item.GT_Wrench_Electric.name',
       'qty': 1,
       'rawName': 'item.gt_wrench_electric'},
 379: {'dmg': 1,
       'id': 14323,
       'maxSize': 1,
       'name': 'Scythe',
       'qty': 1,
       'rawName': 'item.infitool.scythe'},
 380: {'dmg': 39,
       'id': 14321,
       'maxSize': 1,
       'name': 'Dagger',
       'qty': 1,
       'rawName': 'item.infitool.dagger'},
 381: {'dmg': 2,
       'id': 14307,
       'maxSize': 1,
       'name': 'Pickaxe',
       'qty': 1,
       'rawName': 'item.infitool.pickaxe'},
 382: {'dmg': 26,
       'id': 30240,
       'maxSize': 1,
       'name': 'ic2.itemBatLamaCrystal',
       'qty': 1,
       'rawName': 'ic2.itembatlamacrystal'},
 383: {'dmg': 215,
       'id': 267,
       'maxSize': 1,
       'name': 'Iron Sword',
       'qty': 1,
       'rawName': 'item.swordiron'},
 384: {'dmg': 26,
       'id': 30241,
       'maxSize': 1,
       'name': 'ic2.itemBatCrystal',
       'qty': 1,
       'rawName': 'ic2.itembatcrystal'},
 385: {'dmg': 15,
       'id': 30180,
       'maxSize': 1,
       'name': 'ic2.itemArmorBatpack',
       'qty': 1,
       'rawName': 'ic2.itemarmorbatpack'},
 386: {'dmg': 238,
       'id': 27361,
       'maxSize': 64,
       'name': 'item.GT_Dusts.238.name',
       'qty': 165,
       'rawName': 'item.gt_dusts.238'},
 387: {'dmg': 240,
       'id': 27361,
       'maxSize': 64,
       'name': 'item.GT_Dusts.240.name',
       'qty': 1641,
       'rawName': 'item.gt_dusts.240'},
 388: {'dmg': 243,
       'id': 27361,
       'maxSize': 64,
       'name': 'item.GT_Dusts.243.name',
       'qty': 4,
       'rawName': 'item.gt_dusts.243'},
 389: {'dmg': 0,
       'id': 30239,
       'maxSize': 16,
       'name': 'ic2.itemBatREDischarged',
       'qty': 149,
       'rawName': 'ic2.itembatredischarged'},
 390: {'dmg': 1,
       'id': 30235,
       'maxSize': 1,
       'name': 'ic2.itemToolDrill',
       'qty': 1,
       'rawName': 'ic2.itemtooldrill'},
 391: {'beeInfo': {'canSpawn': False,
                   'displayName': 'Rocky',
                   'generation': 0,
                   'hasEffect': False,
                   'health': 30,
                   'ident': 'extrabees.species.rock',
                   'isAlive': True,
                   'isAnalyzed': False,
                   'isIrregularMating': False,
                   'isNatural': True,
                   'isSecret': False,
                   'maxHealth': 30},
       'dmg': 0,
       'id': 13341,
       'maxSize': 1,
       'name': 'Rockybees.princess.adj.add bees.princess',
       'qty': 11,
       'rawName': 'item.beeprincessge'},
 392: {'dmg': 0,
       'id': 6297,
       'maxSize': 1,
       'name': 'item.lootBag.name',
       'qty': 1,
       'rawName': 'item.lootbag'},
 393: {'dmg': 26,
       'id': 30036,
       'maxSize': 1,
       'name': 'ic2.itemAdvBat',
       'qty': 1,
       'rawName': 'ic2.itemadvbat'},
 394: {'dmg': 359,
       'id': 261,
       'maxSize': 1,
       'name': 'Bow',
       'qty': 1,
       'rawName': 'item.bow'},
 395: {'dmg': 1,
       'id': 14311,
       'maxSize': 1,
       'name': 'Broadsword',
       'qty': 1,
       'rawName': 'item.infitool.broadsword'},
 396: {'dmg': 48,
       'id': 267,
       'maxSize': 1,
       'name': 'Iron Sword',
       'qty': 1,
       'rawName': 'item.swordiron'},
 397: {'dmg': 54,
       'id': 278,
       'maxSize': 1,
       'name': 'Diamond Pickaxe',
       'qty': 1,
       'rawName': 'item.pickaxediamond'},
 398: {'dmg': 0,
       'id': 387,
       'maxSize': 1,
       'name': 'Welcome to the DNS',
       'qty': 1,
       'rawName': 'item.writtenbook'}}

target = "diamond"
for k,v in data.iteritems():
    if target in v['name'].lower():
      print v['name'],v['id'],v['dmg']
      print v